[pytest]
python_files = test_*.py
python_classes = Test*
python_functions = test_*


markers =
    ui: Маркировка для UI тестов.
    regression: Маркировка для regression тестов.
    smoke: Маркировка для smoke тестов.
    slow: Маркировка для slow тестов.
    critical: Маркировка для slow тестов.
    registration: Маркировка для тестов, связанных с регистрацией пользователей.
    authorization: Маркировка для тестов, связанных с авторизацией пользователя.